compass:
  ros__parameters:
    compass_publish_seconds: 2.0
    compass_type: fake
gps:
  ros__parameters:
    gps_publish_seconds: 2.0
    gps_type: actual
geo_to_cart:
  ros__parameters:
    ref_latitude: 37.33678616666667
    ref_longitude: -121.88098083333334
task_manager:
  ros__parameters:
    task_types:
      # 1 = GPSNAV, 2 = OBJECTNAV, 3 = ARUCONAV
      - 1
      - 1
      - 2
    task_details:
      - '{"goal_latitude": 101.0, "goal_longitude": 101.0}'
      - '{"goal_latitude": 102.0, "goal_longitude": 102.0}'
      - "{}"
