compass:
  ros__parameters:
    compass_publish_seconds: 2.0
    compass_type: fake
gps:
  ros__parameters:
    gps_publish_seconds: 2.0
    gps_type: fake
geo_to_cart:
  ros__parameters:
    ref_latitude: 90
    ref_longitude: 90