compass:
  ros__parameters:
    compass_publish_seconds: 2.0
    compass_type: fake
gps:
  ros__parameters:
    gps_publish_seconds: 2.0
    gps_type: fake
geo_to_cart:
  ros__parameters:
    ref_latitude: 100
    ref_longitude: 100
task_manager:
  ros__parameters:
    task_types:
      # 1 = GPSNAV, 2 = OBJECTNAV, 3 = ARUCONAV
      - 1
      - 1
      - 2
    task_details:
      - '{"goal_latitude": 101.0, "goal_longitude": 101.0}'
      - '{"goal_latitude": 102.0, "goal_longitude": 102.0}'
      - "{}"
obstacle_mapper:
  ros__parameters:
    update_frequency: 10.0  #Hz
    default_map_width: 200  # Width of the default map in grid cells
    default_map_height: 200  # Height of the default map in grid cells
    default_map_resolution: 0.1  # Resolution of the default map in meters per cell
