compass:
  ros__parameters:
    compass_publish_seconds: 2.0
    compass_type: fake
gps:
  ros__parameters:
    gps_publish_seconds: 2.0
    gps_type: fake
geo_to_cart:
  ros__parameters:
    ref_latitude: 100
    ref_longitude: 100
task_manager:
  ros__parameters:
    task_types:
      # 1 = GPSNAV, 2 = OBJECTNAV, 3 = ARUCONAV
      - 1
      - 1
      - 2
    task_details:
      - '{"goal_latitude": 101.0, "goal_longitude": 101.0}'
      - '{"goal_latitude": 102.0, "goal_longitude": 102.0}'
      - "{}"
map:
  ros__parameters:
    width: 200  # Width of the map in grid cells
    height: 200  # Height of the map in grid cells
    resolution: 0.05  # Resolution of the map in meters per cell
    map_publish_seconds: 1.0  # How often to publish the map, in seconds

obstacle_mapper:
  ros__parameters:
    update_frequency: 10.0  #Hz
    max_recent_detections: 1000  # number of recent detections to keep track of
    max_displayed_detections: 15  # number of closest detections to display coordinates for
