name: Lint

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # format code
      - name: Run black
        uses: psf/black@stable
        with:
          src: "./src"
          options: "" # that way it will format all files instead of just checking
      # commit back any changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Format code
